name = "codeback"
type = "javascript"
account_id = "ab9aa98b3b4a7bb160a39c16be0fabe1"
compatibility_date = "2025-07-25"

[vars]
TOKEN_SECRET = "wugdvuiwduiyv262347t2486"

[[kv_namespaces]]
binding = "CODES"
id = "7f72965eaf22448b9e63ae94774b5458"


[assets]
directory = "./dist"
